config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'static_pages/login'
  get  'static_pages/logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def login
    session[:user_id] = 1
    cookies[:user_id] = 1
    
    redirect_to root_path
  end
  
  def logout
    session.delete :user_id
    cookies.delete :user_id
    
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_apple.html.erb
<!-- meta  -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="apple-mobile-web-app-title" content="PWA Cookie">

<!-- icon  -->
<link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path 'icons/icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= asset_path 'icons/icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path 'icons/icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path 'icons/icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path 'icons/icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path 'icons/icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path 'icons/icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path 'icons/icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'icons/icon-180x180.png' %>">

<!-- splash screen -->
<link rel="apple-touch-startup-image" href="<%= asset_path 'splash/launch-640x1136.png' %>" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'splash/launch-750x1334.png' %>" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'splash/launch-1242x2208.png' %>" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'splash/launch-1125x2436.png' %>" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'splash/launch-1536x2048.png' %>" media="(min-device-width: 768px) and (max-device-width: 1024px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'splash/launch-1668x2224.png' %>" media="(min-device-width: 834px) and (max-device-width: 834px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'splash/launch-2048x2732.png' %>" media="(min-device-width: 1024px) and (max-device-width: 1024px) and (-webkit-min-device-pixel-ratio: 2) and (orientation: portrait)">

app/views/layouts/_favicon.html.erb
<link rel="icon" type="image/png" sizes="192x192"  href="<%= asset_path 'icons/icon-192x192.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'icons/icon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= asset_path 'icons/icon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'icons/icon-16x16.png' %>">

app/views/layouts/_mobile.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/views/layouts/_ms.html.erb
<meta name="msapplication-TileImage" content="<%= asset_path 'icons/icon-144x144.png' %>">
<meta name="msapplication-TileColor" content="#2F3BA2">

app/views/layouts/_pwa.html.erb
<link rel="manifest" href="/manifest.json"/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PWA Cookie Test App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= render 'layouts/pwa' %>
  <%= render 'layouts/favicon' %>
  <%= render 'layouts/mobile' %>
  <%= render 'layouts/apple' %>
  <%= render 'layouts/ms' %>

</head>

<body>
<%= yield %>
</body>
</html>

app/views/static_pages/home.html.erb
<%= link_to '解説（Qiita）',  'https://qiita.com/NaokiIshimura/items/19073a45f994129c40b1', target: '_blank' %>
<br>
<%= link_to 'ソース（Github）', 'https://github.com/NaokiIshimura/Qiita-PWA-Cookie', target: '_blank' %>

<hr>
<%= session[:user_id] == 1 ? 'ログイン済み' : 'ログイン前' %>

<hr>

session[:user_id] = <%= session[:user_id]  %>
<br>
cookies[:user_id] = <%= cookies[:user_id]  %>

<hr>

<%= link_to 'login' , static_pages_login_path %>
<br>
<%= link_to 'logout', static_pages_logout_path %>

<style>
  html {
    font-size: 200%;
  }
</style>